# Generated by Django 5.0.14 on 2025-05-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityExpressAPI', '0002_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_txnid', models.CharField(max_length=30, unique=True)),
                ('pinno', models.CharField(blank=True, max_length=30, null=True)),
                ('sender_first_name', models.CharField(max_length=100)),
                ('sender_last_name', models.CharField(max_length=100)),
                ('sender_gender', models.CharField(max_length=10)),
                ('sender_address', models.CharField(max_length=200)),
                ('sender_city', models.CharField(max_length=100)),
                ('sender_country', models.CharField(max_length=50)),
                ('sender_id_type', models.CharField(max_length=50)),
                ('sender_id_number', models.CharField(max_length=50)),
                ('source_of_fund', models.CharField(max_length=50)),
                ('sender_nationality', models.CharField(max_length=50)),
                ('receiver_first_name', models.CharField(max_length=100)),
                ('receiver_last_name', models.CharField(max_length=100)),
                ('receiver_address', models.CharField(max_length=200)),
                ('receiver_country', models.CharField(max_length=50)),
                ('receiver_contact_number', models.CharField(max_length=20)),
                ('relationship_to_beneficiary', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(max_length=10)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('txn_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
