# Generated by Django 5.0.14 on 2025-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityExpressAPI', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
