# Generated by Django 5.0.14 on 2025-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityExpressAPI', '0004_transaction_remarks_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='response_payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
