# Generated by Django 5.0.14 on 2025-05-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityExpressAPI', '0005_transaction_request_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
