# Generated by Django 5.0.14 on 2025-05-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityExpressAPI', '0006_transaction_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
