# Generated by Django 5.0.14 on 2025-05-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityExpressAPI', '0007_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
