# Generated by Django 5.0.14 on 2025-05-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityExpressAPI', '0008_location_location_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=50)),
                ('request_payload', models.TextField()),
                ('response_payload', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='CityExpressAPI.transaction', to_field='agent_txnid')),
            ],
        ),
    ]
