# Generated by Django 5.0.14 on 2025-05-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityExpressAPI', '0009_transactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20, null=True),
        ),
    ]
