# Generated by Django 5.0.14 on 2025-05-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityExpressAPI', '0010_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
